name: "Test Pipeline with Secrets"

trigger: none

parameters:
  - name: manualTrigger
    displayName: 'Run pipeline manually?'
    type: boolean
    default: false

pool:
  vmImage: 'ubuntu-latest'

stages:

  # ─── STAGE 1: Build ───────────────────────────────────────────────
  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: TestJob
        displayName: 'Test Job'
        steps:

          - script: echo "Triggered manually = ${{ parameters.manualTrigger }}"
            displayName: 'Manual Trigger'

          - script: echo "Secret1 = $(SECRET1)"
            displayName: 'Secret1'

          - script: echo "Secret2 = $(SECRET2)"
            displayName: 'Secret2'

          - script: echo "VAR1 = $(VAR1)"
            displayName: 'VAR1'


