name: "From Azure Vault"

trigger: none

parameters:
  - name: manualTrigger
    displayName: 'Run pipeline manually?'
    type: boolean
    default: false

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: FromVault
    displayName: 'Fetch From Vault'
    jobs:
      - job: VaultJob
        displayName: 'Read Key Vault Secrets'
        steps:

          - task: AzureKeyVault@2
            displayName: 'Fetch secrets from Key Vault'
            inputs:
              azureSubscription: 'Azure subscription 1 (xxxxx)'
              KeyVaultName: 'poc-test'       
              SecretsFilter: 'test1, test2'          
              RunAsPreJob: true

          - script: echo "test1 = $MY_TEST1"
            displayName: 'Print test1'
            env:
              MY_TEST1: $(test1)                     

          - script: echo "test2 = $MY_TEST2"
            displayName: 'Print test2'
            env:
              MY_TEST2: $(test2)                    
